### PR TITLE
update pep8 references to pycodestyle

### PR DESCRIPTION
**Pull request by kfrendrich**

### CODE REVIEW

**Comment by ibqn** [comment]
what is the state here?

**Comment by kfrendrich** [comment]
I use it since months without any problems.

**Comment by victoraraujo01** [comment]
Could you explain how could I install this plugin from source using this specific commit? It seems that it's been a while since pep8 was discontinued and this project hasn't been updated so I was thinking of using your pull request.

**Comment by kfrendrich** [comment]
As I remember, I cloned into this directory "~/.config/sublime-text-3/Packages".
Could you check it please?

**Comment by kiddick** [comment]
Any progress here?

**Comment by kfrendrich** [comment]
If you have any idea about further bugfixes or improvements I can help you.

**Comment by ergdev** [comment]
+1

**Comment by braver** [comment]
Yeah, this will really break everything for a lot of people. I don't see the harm in this little historical artefact.

**Comment by ergdev** [comment]
so does this plugin work if you only have pycodestyle installed on your system?

**Comment by braver** [comment]
Probably not, we’d need a new plugin for that. Renaming everything in this one will wreak havoc, but you’re welcome to fork it into a `pycodestyle` linter plugin.

**Comment by tonyjiangh** [comment]
FYI, Found this repository https://github.com/Tadly/SublimeLinter-pycodestyle

**Comment by ergdev** [comment]
oh nice. I forked it too: https://github.com/ergdev/SublimeLinter-pycodestyle

**Comment by braver** [comment]
Sweet. Can you guys decide which is best? If you want you can transfer the repo to the SublimeLinter organisation, and I'll add you to the maintainers for it. Alternatively, rename it to SublimeLinter-**contrib**-pycodestyle and just open a PR over at https://github.com/SublimeLinter/package_control_channel to publish it.

**Comment by tonyjiangh** [comment]
Don't quite know about the difference. But that repo is not mine, so I don't think I can publish it.
@ergdev Your choice.

**Comment by braver** [comment]
Ok, that one looks good to me. @ergdev what do you want to do with it?

**Comment by ergdev** [comment]
I'd be happy to maintain it if you transfer the fork over.

**Comment by braver** [comment]
Can you transfer SublimeLinter-pycodestyle to the SublimeLinter organization? I’ll then add you as a maintainer.

**Comment by ergdev** [comment]
I cannot transfer the fork because that fork already exists in the SublimeLinter org. Is there a different way?

**Comment by braver** [comment]
Ugh. Yes, there are ways but some manual labor is involved. I'll see what I can do.

**Comment by braver** [comment]
Done: https://github.com/SublimeLinter/SublimeLinter-pycodestyle

**Comment by ergdev** [comment]
great, thanks!

**Pull request closed without merging**
